# -*- coding: utf-8 -*-
"""felicidad.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qu0-SiZ3Roi0__H4gsj8pSYu8flhZM20
"""

import streamlit as st
import pandas as pd
import plotly.express as px

# Cargar datos
df = pd.read_csv("indicadorfelicidadcentroamerica.csv", sep=";", encoding="utf-8")

# Convertir columnas a numéricas
df["Ranking 2022"] = pd.to_numeric(df["Ranking 2022"], errors="coerce")
df["Ranking 2024"] = pd.to_numeric(df["Ranking 2024"], errors="coerce")
df["CambioRanking"] = pd.to_numeric(df["CambioRanking"], errors="coerce")

# Selector de año
year = st.selectbox("Selecciona el año", ["2022", "2024"])

# Preparar datos
df["Ranking"] = df[f"Ranking {year}"]
df_sorted = df.sort_values("Ranking")

# Colores según cambio
df_sorted["Color"] = df_sorted["CambioRanking"].apply(lambda x: "green" if x > 0 else "red" if x < 0 else "gray")

# Crear gráfico
fig = px.bar(
    df_sorted,
    x="Ranking",
    y="Pais",
    orientation="h",
    color="Color",
    color_discrete_map={"green": "limegreen", "red": "tomato", "gray": "lightgray"},
    hover_data=["Ranking", "CambioRanking", "Fuente"]
)

fig.update_layout(
    title=f"Ranking de Felicidad en Centroamérica ({year})",
    xaxis_title="Ranking Mundial (menor es mejor)",
    yaxis_title="País",
    xaxis=dict(autorange="reversed")
)

# Mostrar gráfico
st.plotly_chart(fig, use_container_width=True)